algoritmo "medianota"
// Função: calcular a média entre duas notas
// Autor: Mariana Barbosa
// Data: 09/10/2024
// seção de declarações de variáveis e constantes
var nota1 ,nota2, media: real
inicio
    escreval ("digite a primeira nota")
    leia (nota1)
    escreval ("digite a segunda nota")
    leia (nota2)
    media <- (nota1 + nota2)/2
    escreval ("Média = ",media)
fimalgoritmo
